m1:
  host: macm1.local
  file: eullm-macos-arm64
  report: mac_mini_m1.txt
m4:
  host: macm4.local
  file: eullm-macos-arm64
  report: mac_mini_m4_pro.txt
darkmac:
  host: darkmac.local
  file: eullm-macos-x64
  report: mac_mini_2018_intel.txt
devmac:
  host: devmac.local
  file: eullm-macos-x64
  report: macbookpro_2018_intel.txt
pi5:
  host: peter@12many.local
  file: eullm-linux-arm64
  report: pi5.txt
